sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gPR/sJZH4fefUOzDlkajGTS5walbH3oXbM/R0dONErZ6JzKb7BuNacza3c58uSzvbQ1WxAhDQ+D5eXzn/QnW1j2k69OBjzOircEWb3NMKjt3E/q3LBT9F4asZoOInpGIPX9aDUPCquJDN/bIQKdgJlr8mzShxZHnkK51G2fvJIQqXZDQYZZXkFpHOTlUG8oJl7AfO79A9guYAnshV6ddah5K+ZgTVlfK9JzfADTL5DsZm6hpXItdPkSnbfSt5XnezBArQUJ681eZL7jmS7QyHWZO3bJEergQuwdaWf7+DCm9FBSkPom4+MUqY2nYjt6SW1y1eX9Uj+ga1atSpwY+zkupc01p/KEh2pIWFeR1SHevhzWXlaKrF/tYlhOTOiMt4l0rxcyhJ9rkyjNuuLQwlZyWvN+Hg3fC2VGl2Z0f3sb1I9lsgFVHBzhZYFxiqqgT9bHupPSc4AlFOQunS+JzEqoW/067dUtu9ETpS+S/+Fs6oPKAhkDMIGxdiKb0R7KxT1nwzMntrA8/Kiz5viPX9be/wclo/KF4iAIm4YedYTYsyS934VMzLe7H1nKIstQt4suYhO265cBfrgiPvaul1DZ051mofBeAwmpdqAW9nJExG07JPWGvet+q/dEwhSjohL1rKKJL+FXYo59tMm3M965uuOTaUx0NImemfTIqGdk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/My-Garden-Acquaintance_880
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy